name: linux_django
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - asgiref=3.10.0=py313h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313haa0f9ac_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - contourpy=1.3.3=py313hdb19cb5_0
  - cycler=0.12.1=py313h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - django=5.2.8=py313h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jpeg=9f=h5ce9db8_0
  - kiwisolver=1.4.9=py313h24d9097_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libdeflate=1.22=h5eee18b_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libmpdec=4.0.0=h5eee18b_0
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.10.7=py313h8a257da_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py313hacdc0fc_0
  - mkl_fft=2.1.1=py313h57662e1_0
  - mkl_random=1.3.0=py313h23c847b_0
  - ncurses=6.5=h7934f7d_0
  - numexpr=2.14.1=py313h41d4191_0
  - numpy-base=2.3.5=py313h00548fb_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py313h06a4308_1
  - pandas=2.3.3=py313h23c847b_1
  - pcre2=10.46=hf426167_0
  - pillow=12.0.0=py313h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.13.11=hcf712cf_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=3_cp313
  - pytz=2025.2=py313h06a4308_0
  - readline=8.3=hc2a1206_0
  - seaborn=0.13.2=py313h06a4308_3
  - setuptools=80.9.0=py313h06a4308_0
  - six=1.17.0=py313h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - sqlparse=0.5.3=py313h06a4308_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alembic==1.15.2
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - bcrypt==4.0.1
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.2.1
      - cloudpickle==3.1.2
      - cryptography==46.0.3
      - databricks-sdk==0.76.0
      - distro==1.9.0
      - django-picklefield==3.4.0
      - djangorestframework==3.16.1
      - docker==7.1.0
      - fastapi==0.115.8
      - fastapi-utils==0.8.0
      - filelock==3.20.1
      - flask==3.1.2
      - flask-cors==6.0.2
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.45.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.3.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - httptools==0.7.1
      - huey==2.5.5
      - idna==3.11
      - importlib-metadata==8.7.1
      - ipinfo==5.3.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonref==1.1.0
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mlflow==3.8.0
      - mlflow-skinny==3.8.0
      - mlflow-tracing==3.8.0
      - multidict==6.7.0
      - numpy==2.4.0
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.10.18
      - passlib==1.7.4
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==5.9.8
      - psycopg2-binary==2.9.11
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyjwt==2.7.0
      - pymysql==1.1.2
      - pyparsing==3.3.1
      - python-dotenv==1.2.1
      - python-multipart==0.0.21
      - python-rapidjson==1.14
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-file==3.0.1
      - rich==14.2.0
      - rsa==4.9.1
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - secure==1.0.1
      - smmap==5.0.2
      - sqlalchemy==2.0.45
      - sqlalchemy-utils==0.42.1
      - sqlmodel==0.0.18
      - starlette==0.45.3
      - threadpoolctl==3.6.0
      - tldextract==5.1.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
      - werkzeug==3.1.4
      - yarl==1.22.0
      - zenml==0.93.0
      - zipp==3.23.0
